name: PR status checks
on: [pull_request]
permissions: {}
jobs:
    flake8:
        name: Flake8 linting
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
        -   name: Check out repository
            uses: actions/checkout@v4
            with:
                persist-credentials: false
        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version-file: 'pyproject.toml'
        -   name: Install Python project and dependencies
            run: pip install .[dev]
        -   name: Run flake8
            run: flake8 src tests
    ruff:
        name: Ruff linting
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
        -   name: Check out repository
            uses: actions/checkout@v4
            with:
                persist-credentials: false
        -   name: Run Ruff
            uses: astral-sh/ruff-action@v3
            with:
                src: >-
                    src
                    tests
    zizmor:
        name: Zizmor actions checks
        runs-on: ubuntu-latest
        permissions:
            security-events: write
        steps:
        -   name: Check out repository
            uses: actions/checkout@v4
            with:
                persist-credentials: false
        -   name: Run zizmor 🌈
            uses: zizmorcore/zizmor-action@v0.1.1
